languageCode = "en"
languageName = "English"
weight = 1
title = "Takara"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Linux, various tech topics, or just about anything"
dateFormat = "2 January 2006"

[author]
name = "Yougraj"
image = "Profile.png"
headline = "Linux, various tech topics, or just about anything"
bio = "A buggy coder"
links = []
