[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Tech"
pageRef = "Tech"
identifier = "GF0uJP2MRe"
weight = 20 

[[main]]
name = "Youtube"
pageRef = "youtubevanced"
weight = 30 


[[main]]
name = "Tags"
pageRef = "tags"
weight = 40


[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/yougraj"
weight = 70

[[main]]
identifier = "twitter"
pre = "twitter"
url = "https://twitter.com/yougrajb"
weight = 80

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10
